# Generated by Django 3.2 on 2022-02-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bookingdb_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotdb',
            name='slot',
            field=models.TimeField(),
        ),
    ]
