# Generated by Django 3.2 on 2022-02-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_slotdb_slot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slotdb',
            old_name='slot',
            new_name='slot_start',
        ),
        migrations.AddField(
            model_name='slotdb',
            name='slot_end',
            field=models.TimeField(default=None),
        ),
    ]
