# Generated by Django 3.2 on 2022-02-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_slotdb_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdb',
            name='attended',
            field=models.BooleanField(default=False),
        ),
    ]
